name: Node.js CI build react library

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Install
      run: yarn install
    - name: Build
      run: |
        yarn autoclean
        yarn install
        yarn build
    - name: Deploy Docs to GH Page
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: docs
    - name: Publish to NPM
      run: |
        npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
        npm publish --access public
      env:
        NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
